name: Build & Test dotnet
description: Setup, restore dependencies and build dotnet app

inputs:
  working-dir:
    description: Diretory path containing sln file
    required: true
  github-token:
    description: Github token
    required: true
  app-name:
    description: App name
    required: true
  dotnet-version:
    description: Dotnet version
    required: false
    default: "8"
  unit-tests-csproj:
    description: Unit Tests csproj path with working-dir root
    required: false
  ssl-testing:
    required: false
    description: "Needs to install OpenSSL1.1?"
  publish-artifact:
    description: Publish artifact in github
    required: false

runs:
  using: "composite"
  steps:

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '${{ inputs.dotnet-version }}.0.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ inputs.github-token }}

    - name: Restore
      shell: sh
      run: dotnet restore
      working-directory: ${{ inputs.working-dir }}

    - name: Build (Release)
      shell: sh
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{ inputs.working-dir }}

    - name: Cache OpenSSL 1.1
      id: cache-openssl
      uses: actions/cache@v4
      with:
        path: |
          /usr/local/openssl-1.1.1
          ~/.cache/openssl-src
        key: openssl-1.1.1u-${{ runner.os }}

    # - name: Install OpenSSL 1.1 compatibility
    #   if: ${{ inputs.ssl-testing }}
    #   shell: sh
    #   run: |
    #     if [ ! -d /usr/local/openssl-1.1.1 ]; then
    #       echo "OpenSSL 1.1 not found in cache — building..."
    #       mkdir -p ~/.cache/openssl-src
    #       cd ~/.cache/openssl-src

    #       if [ ! -f openssl-1.1.1u.tar.gz ]; then
    #         sudo apt update
    #         sudo apt install -y build-essential wget
    #         wget https://www.openssl.org/source/openssl-1.1.1u.tar.gz
    #       fi

    #       tar -xvf openssl-1.1.1u.tar.gz
    #       cd openssl-1.1.1u
    #       ./config --prefix=/usr/local/openssl-1.1.1
    #       make
    #       sudo make install
    #       sudo ldconfig
    #     else
    #       echo "✅ OpenSSL 1.1 restored from cache."
    #     fi
      
    #TODO - Add openSSL 1.1 cache
    #OpenSSL1.1 dependency must use ubuntu 20.04, latest versions use the following step
    - name: Install OpenSSL 1.1 compatibility
      if: ${{ inputs.ssl-testing }}
      shell: sh
      run: |
        if [ ! -d /usr/local/openssl-1.1.1 ]; then
          sudo apt update
          sudo apt install -y build-essential wget
          wget https://www.openssl.org/source/openssl-1.1.1u.tar.gz
          tar -xvf openssl-1.1.1u.tar.gz
          cd openssl-1.1.1u
          ./config
          make
          sudo make install
          sudo ldconfig
        fi

    - name: Run tests
      if: ${{ inputs.unit-tests-csproj }}
      shell: sh
      run: dotnet test ${{ inputs.unit-tests-csproj }} --no-build --configuration Release
      working-directory: ${{ inputs.working-dir }}

    - name: Dotnet publish
      if: ${{ inputs.publish-artifact }}
      shell: sh
      run: dotnet publish -c Release -o ./publish
      working-directory: ${{ inputs.working-dir }}

    - name: Upload artifact
      if: ${{ inputs.publish-artifact }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.app-name }}
        path: ./publish