name: Build & Test dotnet
description: Setup, restore dependencies and build dotnet app

inputs:
  working-dir:
    description: Diretory path containing sln file
    required: true
  dotnet-version:
    description: Dotnet version
    required: false
    default: "8"
  github-token:
    description: Github token
    required: true
  unit-tests-csproj:
    description: Unit Tests csproj path with working-dir root
    required: false


runs:
  using: "composite"
  steps:

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '${{ inputs.dotnet-version }}.0.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ inputs.github-token }}

    - name: Restore
      shell: sh
      run: dotnet restore
      working-directory: ${{ inputs.working-dir }}

    - name: Build (Release)
      shell: sh
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{ inputs.working-dir }}

    - name: Run tests
      if: ${{ inputs.unit-tests-csproj }}
      shell: sh
      run: dotnet test ${{ inputs.unit-tests-csproj }} --no-build --verbosity normal
      # working-directory: ${{ inputs.working-dir }}