name: Build and Push image to DockerHub
description: Build dockerfile and push to target docker hub repository

inputs:
  app-name:
    description: App name
    required: true
  docker-hub-username:
    description: Docker hub username
    required: true
  docker-hub-token:
    description: Docker hub user password
    required: true
  docker-hub-repository:
    description: Docker hub app repository
    required: true
  image-tag:
    description: Repository tags
    default: latest-snapshot

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download publish artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.app-name }}
        path: ./code/publish

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-hub-username }}
        password: ${{ inputs.docker-hub-token }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ inputs.docker-hub-username }}/${{ inputs.docker-hub-repository }}:${{ inputs.image-tag }}
          ${{ inputs.docker-hub-username }}/${{ inputs.docker-hub-repository }}:${{ github.sha }}
