name: Publish NuGet package to GitHub Packages

on:
  workflow_call:
    inputs:
      working-dir:
        description: Diretory path containing sln file
        required: true
        type: string

permissions:
  contents: read 
  packages: write

jobs:
  dotnet-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build dotnet
        uses: ./.github/actions/step-dotnet-build
        with:
          nupkg-folder: ./artifacts
          working-dir: ${{ inputs.working-dir }}

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        working-directory: ${{ inputs.working-dir }}

      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ./artifacts

      - name: Push .nupkg to GitHub Packages
        uses: ./.github/actions/step-dotnet-push-nuget
        with:
          nupkg-folder: ./artifacts