name: Publish NuGet package to GitHub Packages

on:
  workflow_call:
    inputs:
      working-dir:
        description: Diretory path containing sln file
        required: true
        type: string
    secrets:
      github-token:
        required: true

permissions:
  contents: read 
  packages: write

jobs:
  dotnet-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build dotnet
        uses: andrejuck/reusable-workflows/.github/actions/step-dotnet-build@main
        with:
          working-dir: ${{ inputs.working-dir }}
          github-token: ${{ secrets.github-token }}

      - name: Pack
        working-directory: ${{ inputs.working-dir }}
        run: | 
          dotnet pack --configuration Release --no-build --output ./artifacts /p:VersionSuffix=alpha.${{ github.run_number }}

      - name: Push .nupkg to GitHub Packages
        uses: andrejuck/reusable-workflows/.github/actions/step-dotnet-push-nuget@main
        with:
          nupkg-folder: ./artifacts