name: Build and Publish image

on:
  workflow_call:
    inputs:
      working-dir:
        description: Diretory path containing sln file
        required: true
        type: string
      app-name:
        description: App name
        required: true
        type: string
      image-tag:
        description: Repository image tag
        default: latest-snapshot
        type: string
        required: false
      dotnet-version:
        description: Dotnet version
        required: false
        default: "8"
        type: string
      unit-tests-csproj:
        description: Unit Tests csproj path with working-dir root
        required: false
        type: string
      ssl-testing:
        required: false
        description: "Needs to install OpenSSL1.1?"
        type: boolean
      publish-artifact:
        description: Publish artifact in github
        required: false
        type: boolean
    secrets:
      github-token:
        required: true
      docker-hub-username:
        required: true
      docker-hub-token:
        required: true
      docker-hub-repository:
        required: true

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build dotnet
        uses: andrejuck/reusable-workflows/.github/actions/step-dotnet-build@main
        with:
          working-dir: ${{ inputs.working-dir }}
          github-token: ${{ secrets.github-token }}
          app-name: ${{ inputs.app-name }}
          publish-artifact: ${{ inputs.publish-artifact }}

  docker-hub-publish:
    runs-on: ubuntu-latest
    needs: dotnet-build
    steps:
      - uses: actions/checkout@v4

      - name: Build and Push image
        uses: andrejuck/reusable-workflows/.github/actions/step-push-dockerhub-img@main
        with:
          docker-hub-username: ${{ secrets.docker-hub-username }}
          docker-hub-token: ${{ secrets.docker-hub-token }}
          docker-hub-repository: ${{ secrets.docker-hub-repository }}
          image-tag: ${{ inputs.image-tag }}
          app-name: ${{ inputs.app-name }}