name: Publish NuGet package LTS to GitHub Packages

on:
  workflow_call:
    inputs:
      working-dir:
        description: Diretory path containing sln file
        required: true
        type: string
    secrets:
      github-token:
        required: true

permissions:
  contents: read 
  packages: write

jobs:
  dotnet-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build dotnet
        uses: ./.github/actions/step-dotnet-build
        with:
          working-dir: ${{ inputs.working-dir }}
          github-token: ${{ secrets.github-token }}

      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ./artifacts

      - name: Push .nupkg to GitHub Packages
        uses: ./.github/actions/step-dotnet-push-nuget
        with:
          nupkg-folder: ./artifacts
          github-token: ${{ secrets.github-token }}